### ISSUE TITLE
Change in Cyberscore multiple submission tool

### ISSUE THREAD

**Issue by hugopeixoto** [KYU49/PSnapOCR#1]
Hello,

This month I changed the form in the multiple record submission page. I think this change breaks this script. Here's one of the things I changed:

Instead of `name="457146-input1"`, the inputs now use `name="records[457146][input1]"`

I hope this helps fix the issue.

**Comment by KYU49** [comment]
Thank you for your helps.
The issue has been fixed in ver. 2.0.2 (ver. 220129)
